<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!--
  <xacro:include filename="$(find husky_description)/urdf/accessories/intel_realsense.urdf.xacro"/>
-->
  <xacro:include filename="husky_mod/accessories/intel_realsense.urdf.xacro"/>

  <xacro:arg name="parent_link_for_sensor" default="control_box" />
  <xacro:property name="_parent_link_for_sensor"
      value="$(arg parent_link_for_sensor)" />

  <!--
    # Name of top-level macro for Realsense camera has been changed after ROS
    # Kinetic: from "intel_realsense_mount" to "realsense_sensor"; and with
    # different parameter names.
  -->
  <xacro:property name="_ros_version" value="$(optenv ROS_VERSION 1)" />
  <xacro:property name="_ros_distro" value="$(optenv ROS_DISTRO)" />
  <xacro:property name="_is_kinetic" value="${_ros_distro == 'kinetic'}" />
  <xacro:property name="_is_kinetic_or_ros2"
    value="${_is_kinetic or (_ros_version == 2)}" />

  <xacro:unless value="${_is_kinetic}">
    <!--
      # NOTE: local copy made of original urdf/_d435.urdf.xacro in
      # realsense2_description package in order to patch original,
      # by commenting out <xacro:include> of material file which leads to
      # xacro complaining about some <material> being redefined.
    -->
    <xacro:include filename="_d435.urdf.xacro" />
<!--
    <xacro:include
      filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
-->
  </xacro:unless>

  <!-- Control Box Properties -->
  <xacro:property name="ctrl_box_width" value="0.52" />
  <xacro:property name="ctrl_box_length" value="0.59" />
  <xacro:property name="ctrl_box_height" value="0.68" />

  <xacro:if value="${True}">
    <!--
      # Front-side mounted/facing camera.
    -->
    <link name="realsense_mount_front"/>
    <joint name="realsense_mount_front_joint" type="fixed">
      <origin xyz="${ctrl_box_width / 2.0} 0 ${ctrl_box_height / 2.0}"
        rpy="0 0 0" />
      <parent link="${_parent_link_for_sensor}"/>
      <child link="realsense_mount_front" />
    </joint>

    <xacro:if value="${_is_kinetic_or_ros2}">
      <xacro:intel_realsense_mount prefix="camera1" topic="realsense_front"
        parent_link="realsense_mount_front"/>
    </xacro:if>
    <xacro:unless value="${_is_kinetic_or_ros2}">
      <xacro:realsense_sensor prefix="camera1" topic="realsense_front"
          parent="realsense_mount_front" include="0">
        <origin xyz="0.0115 0 0.0100" rpy="0 0 0" />
      </xacro:realsense_sensor>
    </xacro:unless>

  </xacro:if>

  <xacro:if value="${True}">
    <!--
      # Right-side mounted/facing camera.
    -->
    <link name="realsense_mount_right"/>
    <joint name="realsense_mount_right_joint" type="fixed">
      <origin xyz="0 -${ctrl_box_length / 2.0} ${ctrl_box_height / 2.0}"
        rpy="0 0 -1.570796" />
      <parent link="${_parent_link_for_sensor}"/>
      <child link="realsense_mount_right" />
    </joint>

    <xacro:if value="${_is_kinetic_or_ros2}">
      <xacro:intel_realsense_mount prefix="camera2" topic="realsense_right"
        parent_link="realsense_mount_right"/>
    </xacro:if>
    <xacro:unless value="${_is_kinetic_or_ros2}">
      <xacro:realsense_sensor prefix="camera2" topic="realsense_right"
          parent="realsense_mount_right" include="0">
        <origin xyz="0.0115 0 0.0100" rpy="0 0 0" />
      </xacro:realsense_sensor>
    </xacro:unless>

  </xacro:if>

</robot>
