# allow_unknown: true
# default_tolerance: 0.0
# visualize_potential: false

# use_dijkstra: true
# use_dijkstra: false

# use_quadratic: true
# use_quadratic: false

# use_grid_path: false
# use_grid_path: true

# old_navfn_behavior: false
# old_navfn_behavior: true

# lethal_cost: 253
# neutral_cost: 50
# cost_factor: 3.0
# publish_potential: True

# orientation_mode: 0

## How to set the orientation of each point (dynamic reconfigure)
## None=0
## Forward=1
## Interpolate=2
## ForwardThenInterpolate=3
## Backward=4
## Leftward=5
## Rightward=6

# orientation_window_size: 1
# outline_map: true

