<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="parent_link_for_custom" default="base_link" />
  <xacro:property name="_parent_link_for_custom"
      value="$(arg parent_link_for_custom)" />

  <!-- Control Box Properties -->
  <xacro:property name="ctrl_box_width" value="0.19" />
<!--
  <xacro:property name="ctrl_box_width" value="0.27" />
-->
  <xacro:property name="ctrl_box_length" value="0.23" />
  <xacro:property name="ctrl_box_height" value="0.175" />

<!--
  <xacro:arg name="box_offset_x" default="-${ctrl_box_width}" />
-->
  <xacro:arg name="box_offset_x" default="0.05" />
<!--
  <xacro:arg name="box_offset_x" default="0.1" />
-->
  <xacro:arg name="box_offset_z" default="0.2" />

  <xacro:property name="ctrl_box_offset_x" value="$(arg box_offset_x)" />
  <xacro:property name="ctrl_box_offset_z" value="$(arg box_offset_z)" />

  <link name="control_box" >
    <visual>
      <geometry>
        <box size="${ctrl_box_width} ${ctrl_box_length} ${ctrl_box_height}" />
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${ctrl_box_width} ${ctrl_box_length} ${ctrl_box_height}" />
      </geometry>
    </collision>
  </link>

  <joint name="control_box_mount_joint" type="fixed">
    <parent link="${_parent_link_for_custom}" />
    <child link="control_box" />
    <origin xyz="${ctrl_box_offset_x} 0
        ${ctrl_box_height/2.0 + ctrl_box_offset_z}" rpy="0 0 0" />
  </joint>

</robot>
